#ifndef AIRSPACECONVERTER_GLOBAL_H
#define AIRSPACECONVERTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AIRSPACECONVERTER_LIBRARY)
#  define AIRSPACECONVERTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AIRSPACECONVERTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AIRSPACECONVERTER_GLOBAL_H
